# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KisanHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'ObjectMapper'
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON', '~> 4.0'
pod 'SVProgressHUD'
pod 'SpreadsheetView'
pod 'DropDown', '2.3.2'
  # Pods for KisanHub

end
